[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_vending_machine = "HBxSXtxCvNC8sK2z8XxF5YsSsGP8Se8MKc6XD9xBkyuf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alby/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
